# Author: Evan Maulana Ibrahim
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root_password
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongodb_data:
